### ISSUE TITLE
SSL Certificate error

### ISSUE THREAD

**Issue by acebelowzero** [marcsello/pyopenvidu#17]
* PyOpenVidu version: 0.2.0
* Python version: 3.8.10
* Operating System: Windows 10
* OpenVidu KMS Docker: 2.16.0
### Description
I was trying to create a OpenVidu object  and got a 
SSL exception

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=4443): Max retries exceeded with url: /sessions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))
````

### What I Did
```
from pyopenvidu import OpenVidu
ov = OpenVidu("https://localhost:4443", "SUPERSECRET")
print(ov.sessions)
```

### Error Output
```
Traceback (most recent call last):
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request  
    self._validate_conn(conn)
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket     
    ssl_sock = _ssl_wrap_socket_impl(
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=4443): Max retries exceeded with url: /sessions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    ov = OpenVidu("https://localhost:4443", "SUPERSECRET")
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/pyopenvidu/openvidu.py", line 39, in __init__
    self.fetch()  # initial fetch
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/pyopenvidu/openvidu.py", line 48, in fetch
    r = self._session.get("sessions")
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/requests_toolbelt/sessions.py", line 64, in request
    return super(BaseUrlSession, self).request(
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Users/micha/SPSAIR/cop/live-surveillance-service/venv/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
request

```

**Comment by marcsello** [comment]
It seems to me that the problem here is simply that requests (used by PyOpenVidu)  does not accept self-signed certificates.
I'll try to come up with an elegant solution to this.

**Comment by acebelowzero** [comment]
Maybe add the ability to pass in an certificate into openvidu object?  Then it would be based into the request 
@marcsello

**Comment by marcsello** [comment]
I've added `verify` and `cert` options to the OpenVidu constructor.
See 33f261cfa63e7bfc5fa67670a2dce66be3e1612f
The next release of PyOpenVidu will have this feature.
